### ISSUE TITLE
No menu item icon on OSX BigSur with Apple Silicone

### ISSUE THREAD

**Issue by Basster** [gathertown/gather-town-desktop-releases#3]
I'm running gather desktop (0.1.6) on OSX 11.6 with Apple Silicone (M1) CPU and I only have a blank "non-icon" on my menu bar for gather.

![image](https://user-images.githubusercontent.com/1265783/140503906-3996764d-5694-486b-bb1b-5715346ef8c9.png)

![Bildschirmfoto 2021-11-05 um 12 29 46](https://user-images.githubusercontent.com/1265783/140504085-0cbb167b-c914-4e2b-ade8-412727263c3f.png)

Menu is working properly, but no icon is shown, neigther in dark-mode.

**Comment by Basster** [comment]
Has nothing to do with the OS version, same issue on OSX 12.0.1

![image](https://user-images.githubusercontent.com/1265783/140910811-b0d3f8b9-88ca-4208-9506-23e8d0b7bc08.png)

**Comment by rain-axb** [comment]
+1 I have same issue.

**Comment by Basster** [comment]
Still valid on gather.town 0.1.7

**Comment by Basster** [comment]
Still valid with gather.town 0.2.0 😴

**Comment by Basster** [comment]
Btw. still valid on gather.town 0.2.1 and MacOS 12.3... 😴 💤

**Comment by Basster** [comment]
Fixed with V3.x (Apple Silicone Build) for me.
