### ISSUE TITLE
0.2.0 - window frame disappeared

### ISSUE THREAD

**Issue by Basster** [gathertown/gather-town-desktop-releases#6]
With the new [0.2.0](https://github.com/gathertown/gather-town-desktop-releases/releases/tag/v0.2.0) version, the application window has no upper border anymore, so no change to grab the window and move it around.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1265783/155329613-b557f05e-6427-4a34-b207-f9781b906d4f.png">

System:
OS: macOS 12.2.1 21D62 arm64
Host: MacBookPro17,1
Kernel: 21.3.0

Seems to be this: https://www.electronjs.org/docs/latest/api/frameless-window/

**Comment by Basster** [comment]
Funny, I see some kind of an "invisible" frame at the bottom of the app window:

![image](https://user-images.githubusercontent.com/1265783/155332416-49b2cc32-98a9-48d0-8296-a64671f6b668.png)
(see my terminal shining through)

If I move my mouse to the edge of this frame I get a resize cursor and sometimes (cannot reproduce it each time) I can drag the window there... 😕

**Comment by fischeversenker** [comment]
It's the same on Windows. This is the top right corner of the app window:
![image](https://user-images.githubusercontent.com/7970458/155488626-c49a2deb-56de-409b-affd-6d5e3f934062.png)

Environment:
Windows 11
Gather 0.2.0

**Comment by andrei0x309** [comment]
The issue was solved in the 0.2.1 release so this issue can be closed.

**Comment by Basster** [comment]
Can confirm that this issue has been solved. I'm going to close it.
